EntityOptions:
  #MythicMobsでショップ作成を行う場合は、ShopにしたいMobのFactionに「NPCShop」が含まれていれば自動で認識します。
  #クリエで名前を付けたネームタグをNPCに付けるとShopの表示名を変更できます。Inventory内は不可。
  UseMythicMobs: false
  DefaultsDisplayName: "&b&lNPCShop"

ShopOptions:
  MaxStackPerItem: 20

Database:
  #jdbc:mariadb
  use: false
  scheme: jdbc:mysql
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  table: npcshop_table



