EntityOptions: #まだ未使用
  #MythicMobsでショップ作成を行う場合は、ShopにしたいMobのFactionに「NPCShop」が含まれていれば自動で認識します。
  UseMythicMobs: false
  DefaultsDisplayName: "&b&lNPCShop"

ShopOptions: #まだ未使用
  MaxStackPerItem: 20

Database:
  use: false
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  table: npcshop_table



