name: NPCShop
version: '1.2.4'
main: net.azisaba.plugin.NPCShop
api-version: '1.20'

load: POSTWORLD
depend:
  - LibsDisguises
  - LoreEditor
softdepend:
  - MythicMobs

commands:
  npcshop:
    permission: npcshop.command.shop
    description: NPCShopのメインコマンド。
    aliases: [ shop, ns ]

permissions:
  npcshop.sql.notifications:
    default: op