name: NPCShop
version: '1.0.0'
main: net.azisaba.plugin.NPCShop
api-version: '1.20'

depend:
  - LibsDisguises
softdepend:
  - MythicMobs

commands:
  shop:
    permission: npcshop.command.shop
    description: NPCShopのメインコマンド。

permissions:
  npcshop.sql.notifications:
    default: op